# Generated by Django 5.1.7 on 2025-03-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='user_address',
            field=models.TextField(default='not yet updated', max_length=600),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='user_image',
            field=models.ImageField(default='default.jpg', upload_to='\\profile pictures'),
        ),
    ]
