# Generated by Django 5.1.7 on 2025-03-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customerprofile_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='user_image',
            field=models.ImageField(default='default.jpg', upload_to='profile pictures/'),
        ),
    ]
