# Generated by Django 5.1.7 on 2025-03-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customerprofile_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='user_image',
            field=models.ImageField(default='default.jpg', upload_to=' \\profileimages'),
        ),
    ]
