# Generated by Django 5.1.7 on 2025-04-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customerprofile_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='user_image',
            field=models.ImageField(default='default.jpg', upload_to=' \\profile pictures'),
        ),
    ]
