# Generated by Django 5.1.7 on 2025-06-17 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0006_alter_customerprofile_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('recipient_phone', models.CharField(default=' ', max_length=11)),
                ('lg_area', models.CharField(default=' ', max_length=100)),
                ('recipient_address', models.TextField(default=' ', max_length=600)),
                ('recipient_name', models.CharField(default=' ', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Shipping Information',
            },
        ),
    ]
