# Generated by Django 5.1.7 on 2025-07-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_shippinginfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUserShippingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(default=' ', max_length=11)),
                ('lg_area', models.CharField(default=' ', max_length=100)),
                ('recipient_address', models.TextField(default=' ', max_length=600)),
                ('recipient_name', models.CharField(default=' ', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Anonymous Users Informations',
            },
        ),
        migrations.AlterModelOptions(
            name='shippinginfo',
            options={'verbose_name_plural': 'Shipping Informations'},
        ),
    ]
