# Generated by Django 5.1.7 on 2025-03-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('quantity', models.IntegerField()),
                ('price', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='\\product_images')),
            ],
        ),
    ]
